@startuml Schema
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define FONTAWESOMEOLD https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome

!include DEVICONS/linux.puml
!include DEVICONS/python.puml
!include DEVICONS/raspberry_pi.puml
!include DEVICONS/aptana.puml
!include DEVICONS/database.puml
!include DEVICONS/html5.puml
!include DEVICONS/docker.puml
!include DEVICONS/mongodb.puml
!include FONTAWESOME/users.puml
!include FONTAWESOME/user.puml
!include FONTAWESOMEOLD/send_o.puml

skinparam backgroundColor #fff

HIDE_STEREOTYPE()

System_Boundary(c1, "Hosted") {
  Container(api, "API", "Python (FastAPI)", "Endpoint to receive and process cocktail data", "python")
  System(mongodb, "Mongodb", "Database to hold the cocktail data", "mongodb")
}
Container(webapp, "WebApp", "Python (Streamlit)", "Displays information and option for the user to filter", "python")
Person_Ext(user, "Users", "Person who wants cocktails and see the data", "users")
System(cocktailberry, "CocktailBerry", "CocktailBerry machines which sends production data", "raspberry_pi")



Rel_L(user, cocktailberry, "uses")
Rel_R(cocktailberry,  user, "cocktails")
Rel(user, webapp, "uses", "https")
Rel(cocktailberry, api, "posts\n(protected)", "https")
Rel_L(webapp, api, "gets\n(open)", "https")
Rel_L(api, mongodb, "saves")
Rel_R(mongodb, api, "provides")


@enduml