@startuml Schema
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define FONTAWESOMEOLD https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome

!include DEVICONS/linux.puml
!include DEVICONS/python.puml
!include DEVICONS/raspberry_pi.puml
!include DEVICONS/aptana.puml
!include DEVICONS/database.puml
!include DEVICONS/html5.puml
!include FONTAWESOME/users.puml
!include FONTAWESOME/user.puml
!include FONTAWESOMEOLD/send_o.puml

skinparam backgroundColor #fff

HIDE_STEREOTYPE()

System_Boundary(c1, "Deta", $link="https://docs.deta.sh/docs/home/") {
  Container(api, "API", "Python (FastAPI)", "Endpoint to receive and process cocktail data", "python")
  Container(detastore, "Deta Store", "Deta", "Saves cocktail data into a NoSql format database", "database")
}
Container(webapp, "WebApp", "Python (Streamlit)", "Displays information and option for the user to filter", "python")
Person_Ext(user, "Users", "Person who wants the exported data from the DB", "users")
System(cocktailberry, "CocktailBerry", "CocktailBerry machines which sends production data", "raspberry_pi")



Rel(user, webapp, "uses", "https")
Rel(cocktailberry, api, "post", "https")
Rel_L(webapp, detastore, "reads", "SDK")
Rel_R(api, detastore, "saves")
Rel_L(detastore, api, "provides")


@enduml