name: Code Check
run-name: 🔍 Code check — ${{ github.event.pull_request.title || 'manual run' }}

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: "3.13"
      - name: 🔍 Lint with ruff
        run: uvx ruff check .
      - name: 🔍 Check formatting with ruff
        run: uvx ruff format . --check

  ty:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: "3.13"
      - name: 🔍 Type Checking with ty
        run: uv run --all-packages ty check
